### ISSUE TITLE
Send messages with enter only

### ISSUE THREAD

**Issue by Radutiu-Horatiu** [leon0707/react-chat-plugin#10]
Hello, maybe add a feature where you can switch to send messages on Enter key only, without Shift+Enter.

**Comment by leon0707** [comment]
Hi, the key combo is optional now. Press enter to send the message when `onSendKey` is not passed with any value

**Comment by Radutiu-Horatiu** [comment]
Hello, sorry to bother but the issue has not been resolved yet. Whatever you write in onSendKey it will still send only with Shift+Enter.

**Comment by leon0707** [comment]
Hi. I checked the test case for InputBox. https://github.com/leon0707/react-chat-plugin/blob/master/tests/InputBox.test.js#L60. It should be fixed.
